dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - psql -U postgres -c "DROP DATABASE \"test_decide\""
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - cd decide
  - cp travis_local_settings.py local_settings.py
  - python ./manage.py test mixnet
if: branch = master
deploy:
  provider: heroku
  app: prepexam121212
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
